AllCops:
  DisplayCopNames: true

#
# Style
#

LineLength:
  Max: 128

Style/StringLiterals:
  EnforcedStyle: double_quotes

#
# Metrics
#

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50
