module Celluloid::Internals; end

require 'celluloid/internals/call_chain'
require 'celluloid/internals/cpu_counter'
require 'celluloid/internals/links'
require 'celluloid/internals/logger'
require 'celluloid/internals/method'
require 'celluloid/internals/properties'
require 'celluloid/internals/handlers'
require 'celluloid/internals/receivers'
require 'celluloid/internals/registry'
require 'celluloid/internals/responses'
require 'celluloid/internals/signals'
require 'celluloid/internals/stack_dump'
require 'celluloid/internals/task_set'
require 'celluloid/internals/thread_handle'
require 'celluloid/internals/uuid'